name: native_assets
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # Due to the way our tests work, this must have the same dependencies as
  # sqlite3_native_assets.
  # It can't depend on sqlite3_native_assets directly however
  sqlite3: ^2.7.4
  hooks: ^0.19.5
  native_toolchain_c: ^0.16.8
  logging: ^1.3.0
  http: ^1.3.0
  archive: ^4.0.2
  path: ^1.9.1
  code_assets: ^0.19.4

dev_dependencies:
  lints: ^5.0.0
  package_config: ^2.2.0
  test: ^1.24.0
  test_descriptor: ^2.0.2
  yaml: ^3.1.3
