[package]
name = "custom_wasm_build"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]

[build-dependencies]
cc = "1.0.46"
cmake = "0.1.50"

[profile.release]
opt-level = "z"
lto=true
