[package]
name = "custom_wasm_build"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
unicode-segmentation = "1.10.1"
unicode-normalization = "0.1.22"

[build-dependencies]
cc = "1.0.46"
cmake = "0.1.50"

[profile.release]
opt-level = "z"
lto=true
