// Generated by tool/protocol_generator.dart, don't modify by hand.
import { WebEndpoint } from "./channel.js";
export const typeOpenRequest = "open";
export const typeConnectRequest = "connect";
export const typeCustomRequest = "custom";
export const typeFileSystemExistsQuery = "fileSystemExists";
export const typeFileSystemFlushRequest = "fileSystemFlush";
export const typeFileSystemAccess = "fileSystemAccess";
export const typeRunQuery = "runQuery";
export const typeRequestExclusiveLock = "exclusiveLock";
export const typeReleaseLock = "releaseLock";
export const typeCloseDatabase = "closeDatabase";
export const typeOpenAdditionalConnection = "openAdditionalConnection";
export const typeSimpleSuccessResponse = "simpleSuccessResponse";
export const typeEndpointResponse = "endpointResponse";
export const typeRowsResponse = "rowsResponse";
export const typeErrorResponse = "errorResponse";
export const typeUpdateStreamRequest = "updateRequest";
export const typeRollbackStreamRequest = "rollbackRequest";
export const typeCommitsStreamRequest = "commitRequest";
export const typeDedicatedCompatibilityCheck = "dedicatedCompatibilityCheck";
export const typeSharedCompatibilityCheck = "sharedCompatibilityCheck";
export const typeDedicatedInSharedCompatibilityCheck =
  "dedicatedInSharedCompatibilityCheck";
export const typeUpdateNotification = "notifyUpdate";
export const typeCommitNotification = "notifyCommit";
export const typeRollbackNotification = "notifyRollback";
export const typeAbortRequest = "abort";
export const typeStopWorkerRequest = "stop";
export type Message =
  | Notification
  | Request
  | Response
  | OpenRequest
  | ConnectRequest
  | CustomRequest
  | FileSystemExistsQuery
  | FileSystemFlushRequest
  | FileSystemAccess
  | RunQuery
  | RequestExclusiveLock
  | ReleaseLock
  | CloseDatabase
  | OpenAdditionalConnection
  | SimpleSuccessResponse
  | EndpointResponse
  | RowsResponse
  | ErrorResponse
  | StreamRequest
  | UpdateStreamRequest
  | RollbackStreamRequest
  | CommitsStreamRequest
  | CompatibilityCheck
  | DedicatedCompatibilityCheck
  | SharedCompatibilityCheck
  | DedicatedInSharedCompatibilityCheck
  | UpdateNotification
  | CommitNotification
  | RollbackNotification
  | AbortRequest
  | StopWorkerRequest;
export type Notification =
  | UpdateNotification
  | CommitNotification
  | RollbackNotification;
export type Request =
  | OpenRequest
  | ConnectRequest
  | CustomRequest
  | FileSystemExistsQuery
  | FileSystemFlushRequest
  | FileSystemAccess
  | RunQuery
  | RequestExclusiveLock
  | ReleaseLock
  | CloseDatabase
  | OpenAdditionalConnection
  | StreamRequest
  | UpdateStreamRequest
  | RollbackStreamRequest
  | CommitsStreamRequest
  | CompatibilityCheck
  | DedicatedCompatibilityCheck
  | SharedCompatibilityCheck
  | DedicatedInSharedCompatibilityCheck;
export type Response =
  | SimpleSuccessResponse
  | EndpointResponse
  | RowsResponse
  | ErrorResponse;
export interface OpenRequest {
  // Dart name: wasmUri
  u: string;
  // Dart name: databaseName
  d: string;
  // Dart name: storageMode
  s: string;
  // Dart name: onlyOpenVfs
  o: boolean;
  // Dart name: additionalData
  a: unknown /* JSAny */ | null;
  // Dart name: requestId
  i: number /* int */;
  // Dart name: type
  t: "open";
}
export interface ConnectRequest {
  // Dart name: endpoint
  r: WebEndpoint;
  // Dart name: requestId
  i: number /* int */;
  // Dart name: databaseId
  d: number /* int */ | null;
  // Dart name: type
  t: "connect";
}
export interface CustomRequest {
  // Dart name: payload
  r: unknown /* JSAny */ | null;
  // Dart name: lockId
  z: number /* int */ | null;
  // Dart name: requestId
  i: number /* int */;
  // Dart name: databaseId
  d: number /* int */ | null;
  // Dart name: type
  t: "custom";
}
export interface FileSystemExistsQuery {
  // Dart name: fsType
  f: number /* int */;
  // Dart name: requestId
  i: number /* int */;
  // Dart name: databaseId
  d: number /* int */ | null;
  // Dart name: type
  t: "fileSystemExists";
}
export interface FileSystemFlushRequest {
  // Dart name: requestId
  i: number /* int */;
  // Dart name: databaseId
  d: number /* int */ | null;
  // Dart name: type
  t: "fileSystemFlush";
}
export interface FileSystemAccess {
  // Dart name: buffer
  b: ArrayBuffer | null;
  // Dart name: fsType
  f: number /* int */;
  // Dart name: requestId
  i: number /* int */;
  // Dart name: databaseId
  d: number /* int */ | null;
  // Dart name: type
  t: "fileSystemAccess";
}
export interface RunQuery {
  // Dart name: sql
  s: string;
  // Dart name: parameters
  p: unknown[];
  // Dart name: typeVector
  v: ArrayBuffer | null;
  // Dart name: lockId
  z: number /* int */ | null;
  // Dart name: returnRows
  r: boolean;
  // Dart name: checkInTransaction
  c: boolean;
  // Dart name: requestId
  i: number /* int */;
  // Dart name: databaseId
  d: number /* int */ | null;
  // Dart name: type
  t: "runQuery";
}
export interface RequestExclusiveLock {
  // Dart name: requestId
  i: number /* int */;
  // Dart name: databaseId
  d: number /* int */ | null;
  // Dart name: type
  t: "exclusiveLock";
}
export interface ReleaseLock {
  // Dart name: lockId
  z: number /* int */;
  // Dart name: requestId
  i: number /* int */;
  // Dart name: databaseId
  d: number /* int */ | null;
  // Dart name: type
  t: "releaseLock";
}
export interface CloseDatabase {
  // Dart name: requestId
  i: number /* int */;
  // Dart name: databaseId
  d: number /* int */ | null;
  // Dart name: type
  t: "closeDatabase";
}
export interface OpenAdditionalConnection {
  // Dart name: requestId
  i: number /* int */;
  // Dart name: databaseId
  d: number /* int */ | null;
  // Dart name: type
  t: "openAdditionalConnection";
}
export interface SimpleSuccessResponse {
  // Dart name: response
  r: unknown /* JSAny */ | null;
  // Dart name: requestId
  i: number /* int */;
  // Dart name: type
  t: "simpleSuccessResponse";
}
export interface EndpointResponse {
  // Dart name: endpoint
  r: WebEndpoint;
  // Dart name: requestId
  i: number /* int */;
  // Dart name: type
  t: "endpointResponse";
}
export interface RowsResponse {
  // Dart name: columnNames
  c: string[] | null;
  // Dart name: tableNames
  n: (string | null)[] | null;
  // Dart name: typeVector
  v: ArrayBuffer | null;
  // Dart name: rows
  r: unknown[][] | null;
  // Dart name: autoCommit
  x: boolean;
  // Dart name: lastInsertRowId
  y: number /* int */;
  // Dart name: requestId
  i: number /* int */;
  // Dart name: type
  t: "rowsResponse";
}
export interface ErrorResponse {
  // Dart name: message
  e: string;
  // Dart name: serializedExceptionType
  s: number | null;
  // Dart name: serializedException
  r: unknown /* JSAny */ | null;
  // Dart name: requestId
  i: number /* int */;
  // Dart name: type
  t: "errorResponse";
}
export type StreamRequest =
  | UpdateStreamRequest
  | RollbackStreamRequest
  | CommitsStreamRequest;
export interface UpdateStreamRequest {
  // Dart name: action
  a: boolean;
  // Dart name: requestId
  i: number /* int */;
  // Dart name: databaseId
  d: number /* int */ | null;
  // Dart name: type
  t: "updateRequest";
}
export interface RollbackStreamRequest {
  // Dart name: action
  a: boolean;
  // Dart name: requestId
  i: number /* int */;
  // Dart name: databaseId
  d: number /* int */ | null;
  // Dart name: type
  t: "rollbackRequest";
}
export interface CommitsStreamRequest {
  // Dart name: action
  a: boolean;
  // Dart name: requestId
  i: number /* int */;
  // Dart name: databaseId
  d: number /* int */ | null;
  // Dart name: type
  t: "commitRequest";
}
export type CompatibilityCheck =
  | DedicatedCompatibilityCheck
  | SharedCompatibilityCheck
  | DedicatedInSharedCompatibilityCheck;
export interface DedicatedCompatibilityCheck {
  // Dart name: databaseName
  d: string | null;
  // Dart name: requestId
  i: number /* int */;
  // Dart name: type
  t: "dedicatedCompatibilityCheck";
}
export interface SharedCompatibilityCheck {
  // Dart name: databaseName
  d: string | null;
  // Dart name: requestId
  i: number /* int */;
  // Dart name: type
  t: "sharedCompatibilityCheck";
}
export interface DedicatedInSharedCompatibilityCheck {
  // Dart name: databaseName
  d: string | null;
  // Dart name: requestId
  i: number /* int */;
  // Dart name: type
  t: "dedicatedInSharedCompatibilityCheck";
}
export interface UpdateNotification {
  // Dart name: updateKind
  k: number /* int */;
  // Dart name: updateTableName
  u: string;
  // Dart name: rowId
  r: number /* int */;
  // Dart name: databaseId
  d: number /* int */;
  // Dart name: type
  t: "notifyUpdate";
}
export interface CommitNotification {
  // Dart name: databaseId
  d: number /* int */;
  // Dart name: type
  t: "notifyCommit";
}
export interface RollbackNotification {
  // Dart name: databaseId
  d: number /* int */;
  // Dart name: type
  t: "notifyRollback";
}
export interface AbortRequest {
  // Dart name: requestId
  i: number /* int */;
  // Dart name: type
  t: "abort";
}
export interface StopWorkerRequest {
  // Dart name: type
  t: "stop";
}
export function extractTransferrable(message: Message): Transferable[] {
  const result: Transferable[] = [];
  switch (message.t) {
    case typeConnectRequest: {
      result.push((message as ConnectRequest).r.port);
      break;
    }
    case typeFileSystemAccess: {
      const bufferTmp = (message as FileSystemAccess).b;
      if (bufferTmp != null) result.push(bufferTmp);
      break;
    }
    case typeRunQuery: {
      const typeVectorTmp = (message as RunQuery).v;
      if (typeVectorTmp != null) result.push(typeVectorTmp);
      break;
    }
    case typeSimpleSuccessResponse: {
      const responseTmp = (message as SimpleSuccessResponse).r;
      if (responseTmp instanceof ArrayBuffer) result.push(responseTmp);
      break;
    }
    case typeEndpointResponse: {
      result.push((message as EndpointResponse).r.port);
      break;
    }
    case typeRowsResponse: {
      const typeVectorTmp = (message as RowsResponse).v;
      if (typeVectorTmp != null) result.push(typeVectorTmp);
      break;
    }
  }
  return result;
}
export function dispatchMessage<T>(
  msg: Message,
  cb: {
    _internal_whenAbortRequest: (message: AbortRequest) => T;
    _internal_whenStopWorkerRequest: (message: StopWorkerRequest) => T;
    _internal_whenNotification: (message: Notification) => T;
    _internal_whenResponse: (message: Response) => T;
    _internal_whenRequest: (message: Request) => T;
  },
): T {
  switch (msg.t) {
    case typeAbortRequest:
      return cb._internal_whenAbortRequest(msg as AbortRequest);
    case typeStopWorkerRequest:
      return cb._internal_whenStopWorkerRequest(msg as StopWorkerRequest);
    case typeUpdateNotification:
    case typeCommitNotification:
    case typeRollbackNotification:
      return cb._internal_whenNotification(msg as Notification);
    case typeSimpleSuccessResponse:
    case typeEndpointResponse:
    case typeRowsResponse:
    case typeErrorResponse:
      return cb._internal_whenResponse(msg as Response);
    default:
      return cb._internal_whenRequest(msg as Request);
  }
}
