// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
@ffi.DefaultAsset(
  'package:sqlite3_connection_pool/sqlite3_connection_pool.dart',
)
library;

import 'dart:ffi' as ffi;
import '' as self;

@ffi.Native<
  ffi.Pointer<ConnectionPool> Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
    ffi.Pointer<ffi.NativeFunction<ffi.Pointer<InitializedPool> Function()>>,
  )
>()
external ffi.Pointer<ConnectionPool> pkg_sqlite3_connection_pool_open(
  ffi.Pointer<ffi.Uint8> name,
  int name_len,
  ffi.Pointer<ffi.NativeFunction<ffi.Pointer<InitializedPool> Function()>>
  initialize,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ConnectionPool>)>()
external void pkg_sqlite3_connection_pool_close(
  ffi.Pointer<ConnectionPool> pool,
);

@ffi.Native<
  ffi.Pointer<PoolRequest> Function(
    ffi.Pointer<ConnectionPool>,
    ffi.Int64,
    ffi.Int64,
  )
>(isLeaf: true)
external ffi.Pointer<PoolRequest> pkg_sqlite3_connection_pool_obtain_read(
  ffi.Pointer<ConnectionPool> pool,
  int tag,
  int port,
);

@ffi.Native<
  ffi.Pointer<PoolRequest> Function(
    ffi.Pointer<ConnectionPool>,
    ffi.Int64,
    ffi.Int64,
  )
>(isLeaf: true)
external ffi.Pointer<PoolRequest> pkg_sqlite3_connection_pool_obtain_write(
  ffi.Pointer<ConnectionPool> pool,
  int tag,
  int port,
);

@ffi.Native<
  ffi.Pointer<PoolRequest> Function(
    ffi.Pointer<ConnectionPool>,
    ffi.Int64,
    ffi.Int64,
  )
>(isLeaf: true)
external ffi.Pointer<PoolRequest> pkg_sqlite3_connection_pool_obtain_exclusive(
  ffi.Pointer<ConnectionPool> pool,
  int tag,
  int port,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<PoolRequest>)>()
external void pkg_sqlite3_connection_pool_request_close(
  ffi.Pointer<PoolRequest> request,
);

const addresses = _SymbolAddresses();

class _SymbolAddresses {
  const _SymbolAddresses();
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ConnectionPool>)>
  >
  get pkg_sqlite3_connection_pool_close =>
      ffi.Native.addressOf(self.pkg_sqlite3_connection_pool_close);
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<PoolRequest>)>>
  get pkg_sqlite3_connection_pool_request_close =>
      ffi.Native.addressOf(self.pkg_sqlite3_connection_pool_request_close);
}

final class ConnectionPool extends ffi.Opaque {}

final class PoolRequest extends ffi.Opaque {}

final class ExternalFunctions extends ffi.Struct {
  external ffi.Pointer<
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>)>
  >
  sqlite3_close_v2;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Int Function(ffi.Int64, ffi.Pointer<ffi.Void>)>
  >
  dart_post_c_object;
}

final class InitializedPool extends ffi.Struct {
  external ExternalFunctions functions;

  external ffi.Pointer<ffi.Void> write;

  external ffi.Pointer<ffi.Pointer<ffi.Void>> reads;

  @ffi.UintPtr()
  external int read_count;
}
