name: custom_extension_native_assets
publish_to: none
resolution: workspace

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  sqlite3:
  sqlite3_native_assets: 

  code_assets: ^0.19.7
  hooks: ^0.20.1
  http: ^1.5.0
  tar: ^2.0.0
