// This file contains hashes of SQLite binaries downloaded by the default hook.
// For tests, it is replaced with actual assets. For releases, a pre-release
// check asserts it's up-to-date.
//
// Generated by tool/write_asset_hashes.dart

// dart format off
// ignore: unnecessary_nullable_for_final_variable_declarations
const String? releaseTag = 'sqlite3-3.0.1';

const Map<String, String> assetNameToSha256Hash = {
  'libsqlite3.arm.android.so': '0fae9fdc2b506ecfd17c0bf5687a7930129385ac38214251ad74b3d818144ddb',
  'libsqlite3.arm.linux.so': 'bd489e8ddddc63bc90f5f4065212074524fb63eb285d7ccd65c8bafcbcaaf3a2',
  'libsqlite3.arm64.android.so': '2f8e5a9f1c811c337eba479853b258d18083c4104245bae1c4c3d8693d178086',
  'libsqlite3.arm64.ios.dylib': '679fde366cf245ab12ff536e47c9d2fc231a66e52befa628bd8307f53963fce1',
  'libsqlite3.arm64.ios_sim.dylib': '079ae8d405cdd024b7471f6d737e370dca738a2b9072a0c7e107890a76d01d3d',
  'libsqlite3.arm64.linux.so': 'b5dcf2fd14e8ac403dd37c857d352d78fcc228762ed446afe86d73b763fdbece',
  'libsqlite3.arm64.macos.dylib': '5e41e8e277e4eb065002974b27fbe2b1f2d5871e30465f61169629be7c01d078',
  'libsqlite3.ia32.android.so': 'b05de6fae0a75deff6932c132bc7ed4cfd608835148ea665ea561d1f75946780',
  'libsqlite3.ia32.linux.so': 'cb02c6be890d095c6d4aded055cadaf210958b4f0c8497da221d9e8d76f82d24',
  'libsqlite3.riscv64.linux.so': '651ab9aa75a527a420f2804510dd9bb20457c60231b3a152d20295d63a962398',
  'libsqlite3.x64.android.so': '43eca2b9598fb246cbeba24f7b93659e81a04635dc12656d1b9b9d1b077e023c',
  'libsqlite3.x64.ios_sim.dylib': '8b5e8469c18879db90eada159065aa3567e85900a3b011031d511c7db62a8f7c',
  'libsqlite3.x64.linux.so': 'd68c5f328680ed4797091e84d8bc53e479918c30c2a4ade4c2cfad38556f89da',
  'libsqlite3.x64.macos.dylib': 'eef580b1832c7353aeaab23449bed8e9bceaebaabf0366a4367a4f3de8a5f877',
  'libsqlite3mc.arm.android.so': '6eecdc0f6511e84b05230ac596fcf0833c0b98523fc1770e426d6352bb69d7ac',
  'libsqlite3mc.arm.linux.so': '3f93e348014572549da97e56e468c8396fa90474e734f3d333066276f6d7fa06',
  'libsqlite3mc.arm64.android.so': '94afd4765d43a71bf8886ca0aff102ed808aed18835ce74545e563e25c962f6a',
  'libsqlite3mc.arm64.ios.dylib': '46ae47d469880ec90142222b6fef0554e068c2c7b3484ba36cbde9016e49ce70',
  'libsqlite3mc.arm64.ios_sim.dylib': '25ef04f95090373b1dacd9334bbabc38231f2f36f213ff1306495e204a44afb7',
  'libsqlite3mc.arm64.linux.so': 'bffd19c5892c9d792fed30a4abeeffb0fd6a3a0836b814cddb75704c807bf2ec',
  'libsqlite3mc.arm64.macos.dylib': '2c6106057c265dc31d953cacb045cad69a9ac9fe32dd7dd76cedbe8ab0adce05',
  'libsqlite3mc.ia32.android.so': 'a5edfd848aedabb05d2dd107193b8963d37652c4aae25206de7bb76926c27ef6',
  'libsqlite3mc.riscv64.linux.so': 'baeec8120e704fc0b0e3b2e4646ac3a08bb933ee9097c9f0f9ae41148d7a0f42',
  'libsqlite3mc.x64.android.so': '9d5cca823e60a8576552ecb9d804a7e6f63d8be75d00e851ae41e0e8f2b36221',
  'libsqlite3mc.x64.ios_sim.dylib': 'df2b1bdb88b35a222c75a9474a9b0bb1aab5e33b5eec32aacc80c0d24a6718af',
  'libsqlite3mc.x64.linux.so': 'd09fa946bea63768bbb954e9f3d00e7a3f28209d38c425ab8febfb6f6eb9fbd0',
  'libsqlite3mc.x64.macos.dylib': 'a8d210e84c56e5b0c210d86db9ddc3bd18d92a4168f53e861409ea54ea0dc6dc',
  'sqlite3.arm64.windows.dll': '934b2b6585d523f4ec8ad4b393c769c143f547dc4167d1e6d3451d08cdd1fd01',
  'sqlite3.debug.wasm': '595500b3ea585904f05d07603bb199a4f347402263dd492fba8cd524ac9d5e0f',
  'sqlite3.ia32.windows.dll': '0c1867baa605f219f0185b84117118bef4809b480ee5a4d68a3a6a767854aad5',
  'sqlite3.wasm': '0e22c510e90b1be2757b2d63f6325bb5a771a5cf045f6164dd110025bdf8838d',
  'sqlite3.x64.windows.dll': '0346fa010bb70ea04a08d6a6c88e8ac3041b03171ac95a4c8252e55c219cb7e3',
  'sqlite3mc.arm64.windows.dll': 'd773d07e63bfee813cb68a6f39648c0397f244c045c7e4c3194653eb7ab2c734',
  'sqlite3mc.ia32.windows.dll': '8411174b6ef6766ca51190de3d5181a5effd10221e7234980f685c097897e883',
  'sqlite3mc.wasm': '3829c47c0db1b9e01112a0734812ff542e1d8ef354bbb693446255f65c8cc3a1',
  'sqlite3mc.x64.windows.dll': 'dc5e4a401c88e4db6a632e44747695d949517c2d9bb7f17833d6b5d9d26da8db',
};
