// This file contains hashes of SQLite binaries downloaded by the default hook.
// For tests, it is replaced with actual assets. For releases, a pre-release
// check asserts it's up-to-date.
//
// Generated by tool/write_asset_hashes.dart

// dart format off
// ignore: unnecessary_nullable_for_final_variable_declarations
const String? releaseTag = 'sqlite3-3.1.6';

const Map<String, String> assetNameToSha256Hash = {
  'libsqlite3.arm.android.so': '1c5a8a32d83ddfd24c0301e9b02ed3ccb6526210b26543077f43f7821d83c53b',
  'libsqlite3.arm.linux.so': 'bccd67f3dd3cd89884149860ad45daabbdec2dfab67ce9b296ce4d95febbf5c1',
  'libsqlite3.arm64.android.so': 'a668d1e737597845655ab5a2fe8acee4ef286f08bb642988b7ab1ff183511171',
  'libsqlite3.arm64.ios.dylib': '89b9eabe28b9b6cf4bf68265048eff87fa7b34724872aa51fd823eee922da600',
  'libsqlite3.arm64.ios_sim.dylib': '1ae6181534e3c35eab283c3a1eb9878f5eee19481624085cb54c9debf703d44f',
  'libsqlite3.arm64.linux.so': '28fbd34ad6fbe9776156f364987b32018ca37ac9480a8e11b1863814e4380b72',
  'libsqlite3.arm64.macos.dylib': 'a0af11d9328431c8efb958f270166dcdbfee8f4fe50366962b3605c172906024',
  'libsqlite3.ia32.android.so': '4a7e25ba694ecb29317eb927eb2426370588c60127df4cc566f0327604c78386',
  'libsqlite3.ia32.linux.so': 'fed723e829cf01a233d5c84d441b2dee6bdd2b0243de8de0a8a7459e44f643fe',
  'libsqlite3.riscv64.linux.so': 'adac15fac9ce2d6fc571095999d849d486033e34e7f78dd1c59bc1ccc152cbe2',
  'libsqlite3.x64.android.so': '94bad470dad73ebd8bb205b2d773babe0a6189617d5385461377de28a68c9922',
  'libsqlite3.x64.ios_sim.dylib': '4429cd568941489144ad75b2fec1ff10b9eb569051e1f8d5c0706e144f84c9df',
  'libsqlite3.x64.linux.so': 'dd603e47a15721c5917b463ccbcdea53bee3cd16f3ddf9bd499335d04069ed45',
  'libsqlite3.x64.macos.dylib': '41c6c2a5bcb49f1ae3ff7cd84cff3fd98fc84bd3da3fb3fbd356e319c1d48f99',
  'libsqlite3mc.arm.android.so': 'dffea6f9b8bed51f28e5d64eb87c328a27c420eb64e9d483e917c302652157f6',
  'libsqlite3mc.arm.linux.so': '794866d9c5fbe0d494bbe9e1a9383dce0e23f5ff86f89fd1f144f881862535c2',
  'libsqlite3mc.arm64.android.so': '3cb2dbb6e2916e2f71b494989070c2bd0dce8c3fa7be1a51c3854f71c66ea650',
  'libsqlite3mc.arm64.ios.dylib': 'f39fcc146840a5157944713a33f6f632df36056e4a5b7893f2c940054687bdb3',
  'libsqlite3mc.arm64.ios_sim.dylib': '26fa06c12762f61c5cbc83257e5cd0f3cc3fa839c302b3989ce21d118f7c07c2',
  'libsqlite3mc.arm64.linux.so': '0abffe310f858a0d176fdfa8c83c439b6b902844a83311b714fe500f6b22553c',
  'libsqlite3mc.arm64.macos.dylib': '2aea96cb7f8d92b048ee51ad30c444ed8d9ae7f0ad2bed3f33a46f06ddd61d7f',
  'libsqlite3mc.ia32.android.so': '762f13bddbad387166084f647fcee29b98ecfbad180bb6b25080f044e9b7cc32',
  'libsqlite3mc.riscv64.linux.so': '5be36677c16473b9dec8f12032fc7a7753125c3f2087330df0cecebc140a4397',
  'libsqlite3mc.x64.android.so': 'd2724846293d39152ca78d739cad320f6d45153f52a97f22d17fd9e75d505a63',
  'libsqlite3mc.x64.ios_sim.dylib': 'd75e0ab22b9cc6c859b257160fba0fefbd4a21bce451611292707d6636bbd879',
  'libsqlite3mc.x64.linux.so': 'd3cab48a6f290aa4980d62b86b1c931b8621319dd07e12a9f983e90fc1580e6a',
  'libsqlite3mc.x64.macos.dylib': 'c4866b579b272c160ec0e664092c5f5de01fd2e4a5d77a2e87db40018ce674d3',
  'sqlite3.arm64.windows.dll': '7b412e7471656c7c9752042b235eb5528437baf424b8af47580bf345d6804414',
  'sqlite3.debug.wasm': '7d84b4a7c59080730150703bbc9cc1dc69ae01cfa9eb9ab30f64fcf609d558f6',
  'sqlite3.ia32.windows.dll': '22313add5e74f5a9684496a589d56a72fd80d2aae5dbcf924512d858ea22f743',
  'sqlite3.wasm': 'c41558c74d0ad954c2ece9d8c40ae9c3f247b4ae1c022eeb9899de44b37b9a39',
  'sqlite3.x64.windows.dll': 'c7421f36b1398ec211319cc2570f95f4435fb9b27ac9c5931c7e5cacb8fa20d8',
  'sqlite3mc.arm64.windows.dll': 'bd17eecd909bfc70e38b410b307cb80db87107a04b1bed70464bb51323a8ee92',
  'sqlite3mc.ia32.windows.dll': '7d035b30ba1d6712fd1a060574eebeabbfd47981e4a34dd039cb77149e36e1b6',
  'sqlite3mc.wasm': 'c0d7031175e4fc8611191ea54b03af69fc8442a2e6430b8981444aaa9e644db8',
  'sqlite3mc.x64.windows.dll': '8c6aed11867bd5b5f7e75e3fff200086c5bfa42b6600970750ed592930691701',
};
