// This file contains hashes of SQLite binaries downloaded by the default hook.
// For tests, it is replaced with actual assets. For releases, a pre-release
// check asserts it's up-to-date.
//
// Generated by tool/write_asset_hashes.dart

// dart format off
// ignore: unnecessary_nullable_for_final_variable_declarations
const String? releaseTag = 'sqlite3-3.0.0-beta.0';

const Map<String, String> assetNameToSha256Hash = {
  'android-aarch64-sqlite3.so': '3c7cb99727c6719a4a74fccb9da9b424f4facb135256af0b4c4a60ecb7fd0312',
  'android-aarch64-sqlite3mc.so': '910c89f51f158d1417a67886d55237a34f910c5f54bda87c63021597b5713036',
  'android-armv7a-sqlite3.so': '41fa74f2f65ff8ebd1ae81b22ff98f74db485f72333c5892a0ac9328294df0bb',
  'android-armv7a-sqlite3mc.so': 'd7745b503720b789ce4a11f2b46c10e28dfa23fc4b01c5c7de06a70134da1b8e',
  'android-x64-sqlite3.so': '138a3c5116d6414cb65d6c9c604b31ccc37b7efee06b83f5c3a1640e0cc781c7',
  'android-x64-sqlite3mc.so': 'cdb1196335863da5bd60448662aad192a68e328f1abd269b7732f3ca9414070d',
  'android-x86-sqlite3.so': '33b2c9605ed443b3d2e005ddca1a2106f9ca0c40d44177e5fdccda22957e3b96',
  'android-x86-sqlite3mc.so': 'c5137bc9cd57ef893de3ff941241b9a5e47bc549e2e0681a169f480cb6c6ae95',
  'ios-aarch64-sqlite3.dylib': '4bdcc93541b989dd38db1450dd87a92045e1e1703d183af6468b96fb4e7ab903',
  'ios-aarch64-sqlite3mc.dylib': 'ca37ea9636b5ca1383d7cf5e6a03428dede5143aec1d6059bea940dde055286a',
  'ios-sim-aarch64-sqlite3.dylib': '58f271c899a9eb8b9d058859a499c066faaa68e88d547583a6735527f79a816d',
  'ios-sim-aarch64-sqlite3mc.dylib': 'd5df118b7f65cd42c596109f8a175f66853d68c586a70b2acc552c0a1ef599a3',
  'ios-sim-x64-sqlite3.dylib': '8c691f8be7c5ad22fb8b52447d096da3e790970ef0a1641babfe922f260d2b3a',
  'ios-sim-x64-sqlite3mc.dylib': 'ecd15ed38ab8bedaa6bb06d5d51d78e7c1d44e14321b8a62537abfea49d005f9',
  'linux-aarch64-sqlite3.so': '637c210df8dedc3fca3e450b0904afb7adfc7762c62a85971eb05198e6a6bfe9',
  'linux-aarch64-sqlite3mc.so': 'e42b693da5a6bef8d94ceb319066f141ecef96f54598342bb6c6d0c3e4dfe4c4',
  'linux-armv7-sqlite3.so': '135fa348fcac1efd928cfba5c148b122c033218942a073b91c04ba6a0678a865',
  'linux-armv7-sqlite3mc.so': 'f9d1f2477dac19f82a720d05c8534ae056290fd74a48983ccd8957ae77bd81ed',
  'linux-riscv64gc-sqlite3.so': '0264348f2e74210a192c8b7e1af60718d9f861da867e469653a5e5e9ea7df2a6',
  'linux-riscv64gc-sqlite3mc.so': '9a259b94569c34108cb688e02377bc3e14994f814690e865949531cdb4dd3d7e',
  'linux-x64-sqlite3.so': 'ec969a03f716e79dafbd5f225e791f6d9705d59535315c2aace771deb75dba33',
  'linux-x64-sqlite3mc.so': '385713856163895ec92b0b796aba731dfbafa8f4ca5ffd4182a8d13ea7a48898',
  'linux-x86-sqlite3.so': '5067d6cfdaa20f5a5f41bb1899a5c503927235d21a2bb8768c7ab445025323bd',
  'macos-aarch64-sqlite3.dylib': 'e688150a743cc69b2bd4b2953766ff09074c9c29b306da117c132b48aa0ac9eb',
  'macos-aarch64-sqlite3mc.dylib': '4f79e256255bbca1e3e817672d42e31504e1c57ebaeae4c88213729ca1b1029a',
  'macos-x64-sqlite3.dylib': 'fa9ccbefdff9940a918a6ff0464aa0d2d213cb03aa05951e5be59b856303827e',
  'macos-x64-sqlite3mc.dylib': '6ff97d6b6aeda5a6dbb68f2db0f53382bf861a431f4b17ffbb8c2d083cf2da18',
  'sqlite3.debug.wasm': '81d4f31319509b16d196b0742a474b0cfc20e0d396ebc1c4742d40633c9b8a5e',
  'sqlite3.wasm': '2f15c824a63503525e957c34454db27fc8122de374d71a6b0a743dc16d675cba',
  'sqlite3mc.wasm': 'a36530f62b28fa5f8abb2f569d575330e0a7735f7e8eec1bfebaeb0e27aa0016',
  'win-aarch64-sqlite3.dll': 'fbc381fc6a9f6135aa815c8522b4b81a2f47a4ac25f654ef6fac0b118be70592',
  'win-aarch64-sqlite3mc.dll': 'f8d57aa58befc0b3300d222977fccc036a251b2951bd87ffa3f879a71c05a84a',
  'win-x64-sqlite3.dll': '24ea06bc7fd08df2ade1e420b1bde0965016676904aca47963a2367f89f4fed7',
  'win-x64-sqlite3mc.dll': '0dbc5d412d0b14f320482a664e4c160a896ef9d294d9429d30ed3f43321684aa',
  'win-x86-sqlite3.dll': '87155b39393a576a13c2e9b655a8e9a874e3f0a0cd165dd88d4ea6e42418745a',
  'win-x86-sqlite3mc.dll': 'e99f8e735606cfc6110e9ba053f7387d6c66a88c81a742dbb88bf6f08607ca9d',
};
