#define WASI_EMULATED_MMAN


// Don't include the default VFS implementations, we write our own
#define SQLITE_OS_OTHER 1

// Don't include locking code
#define SQLITE_THREADSAFE 0

// Recommended options
#define SQLITE_DQS 0
#define SQLITE_DEFAULT_MEMSTATIUS 0
#define SQLITE_DEFAULT_WAL_SYNCHRONOUS 1
#define SQLITE_LIKE_DOESNT_MATCH_BLOBS 1
#define SQLITE_MAX_EXPR_DEPTH 0
#define SQLITE_OMIT_SHARED_CACHE
#define SQLITE_USE_ALLOCA
#define SQLITE_BYTEORDER 1234

#define SQLITE_ENABLE_FTS5
#define SQLITE_ENABLE_MATH_FUNCTIONS
#define SQLITE_ENABLE_RTREE

// Disable things we don't need
#define SQLITE_OMIT_DECLTYPE
#define SQLITE_OMIT_DEPRECATED
#define SQLITE_OMIT_PROGRESS_CALLBACK
#define SQLITE_OMIT_AUTHORIZATION
#define SQLITE_UNTESTABLE
#define SQLITE_OMIT_COMPILEOPTION_DIAGS
#define SQLITE_OMIT_LOAD_EXTENSION
#define SQLITE_OMIT_SHARED_CACHE
#define SQLITE_OMIT_TCL_VARIABLE
#define SQLITE_OMIT_UTF16
