import 'dart:io';

import 'package:dart_style/dart_style.dart';
import 'package:ffigen/ffigen.dart';
import 'package:ffigen/src/config_provider/config_types.dart';
import 'package:ffigen/src/config_provider/spec_utils.dart';
import 'package:ffigen/src/code_generator.dart';
import 'package:ffigen/src/context.dart';
import 'package:ffigen/src/header_parser.dart' as ffigen;
import 'package:logging/logging.dart';

import '../../sqlite3_wasm_build/tool/wasm_symbols.dart';

void main() {
  Logger.root.onRecord.listen(print);

  _ffigen();
  writeUsedSymbols();
  writeWasmDefinitions();
}

FfiGenerator createGenerator(
  bool Function(Declaration) filter, {
  List<String> headers = const ['assets/sqlite3.h'],
}) {
  return FfiGenerator(
    output: Output(
      dartFile: Uri.parse('lib/src/ffi/libsqlite3.g.dart'),
      preamble: '// ignore_for_file: type=lint',
      style: NativeExternalBindings(
        assetId: 'package:sqlite3/src/ffi/libsqlite3.g.dart',
      ),
    ),
    headers: Headers(
      entryPoints: [for (final header in headers) Uri.parse(header)],
    ),
    structs: Structs(include: filter),
    functions: Functions(
      include: filter,
      includeSymbolAddress: Declarations.includeAll,
      varArgs: makeVarArgFunctionsMapping({
        'sqlite3_db_config': [
          RawVarArgFunction('', ['int', 'int*']),
        ],
      }, const {}),
      isLeaf: (decl) => _leafFunctions.contains(decl.originalName),
    ),
    globals: Globals(include: _includeSqlite3Only),
  );
}

void _ffigen() {
  createGenerator(_includeSqlite3Only).generate();
}

bool _includeSqlite3Only(Declaration declaration) =>
    declaration.isSqlite3Symbol;

extension on Declaration {
  bool get isSqlite3Symbol => originalName.startsWith('sqlite3');
}

void writeWasmDefinitions() {
  bool filter(Declaration d) {
    return stableFunctions.contains(d.originalName) ||
        unstable.contains(d.originalName);
  }

  final generator = createGenerator(
    filter,
    headers: ['assets/sqlite3_dart_wasm.h', 'assets/sqlite3.h'],
  );

  final library = ffigen.parse(Context(Logger.root, generator));
  final buffer = StringBuffer('''
import 'dart:js_interop';

import 'package:web/web.dart' show Global;

// ignore_for_file: non_constant_identifier_names
typedef Pointer = int;

/// Typed wrappers around the symbols exported by SQLite.
///
/// Generated by `tool/generate_bindings.dart`.
extension type SqliteExports(JSObject raw) implements JSObject {
''');

  void writeType(Type type) {
    const bigIntInJs = ['Int64', 'Uint64', 'Long'];

    switch (type) {
      case PointerType():
        if (type.child.getNativeType() == 'externref ') {
          buffer.write('ExternalDartReference<Object>?');
        } else {
          buffer.write('Pointer /*<${type.getNativeType().trim()}>*/');
        }

        return;
      case NativeType():
        if (bigIntInJs.contains(type.toString())) {
          buffer.write('JSBigInt');
          return;
        }
      case ImportedType():
        if (bigIntInJs.contains(type.cType)) {
          buffer.write('JSBigInt');
          return;
        }
    }

    buffer.write(type.getDartType(library.context));
  }

  for (final binding in library.bindings) {
    final mayBeAbsent = !stableFunctions.contains(binding.originalName);

    switch (binding) {
      case Func():
        buffer.write('external ');
        if (mayBeAbsent) {
          buffer.writeln('JSFunction? get ${binding.originalName};');
        } else {
          final type = binding.functionType;
          writeType(type.returnType);
          buffer.write(' ${binding.originalName}(');

          for (final (i, arg) in type.parameters.indexed) {
            if (i != 0) {
              buffer.write(', ');
            }

            writeType(arg.type);
            buffer.write(' ${arg.name}');
          }

          buffer.writeln(');');
        }

      case Global():
        var jsType = 'Global';
        if (mayBeAbsent) {
          jsType += '?';
        }

        buffer
          ..write('external $jsType get ')
          ..write(binding.originalName)
          ..writeln(';');
    }
  }

  buffer.writeln('}');

  final formatter = DartFormatter(languageVersion: Version(3, 10, 0));
  File(
    'lib/src/wasm/sqlite3_wasm.g.dart',
  ).writeAsStringSync(formatter.format(buffer.toString()));
}

void writeUsedSymbols() {
  final buffer = StringBuffer('''
// Generated by tool/generate_bindings.dart
// Used to generate a linker script hiding functions we don't need.

// dart format off
const usedSqliteSymbols = {
''');
  final library = ffigen.parse(
    Context(Logger.root, createGenerator(_includeSqlite3Only)),
  );

  for (final binding in library.bindings) {
    if (binding is Global || binding is Func) {
      buffer.writeln("  '${binding.originalName}',");
    }
  }

  buffer.writeln('};');
  File(
    'lib/src/hook/compile/used_symbols.dart',
  ).writeAsString(buffer.toString());
}

/// Note: Leaf functions must never call back into Dart.
///
/// Almost all SQLite functions could do that (e.g. due to an update hook, a
/// user-defined function, or a VFS). So we only enable this on a few trivial
/// functions to reduce their overhead.
const _leafFunctions = <String>{
  'sqlite3_last_insert_rowid',
  'sqlite3_changes',
  'sqlite3_get_autocommit',
  // Just to configure the hook itself, it's invoked from sqlite3_step which
  // can't be a leaf function.
  'sqlite3_update_hook',
  'sqlite3_commit_hook',
  'sqlite3_rollback_hook',
  'sqlite3_stmt_isexplain',
  'sqlite3_stmt_readonly',
  'sqlite3_column_count',
  'sqlite3_bind_parameter_count',
};
