// Generated by tool/protocol_generator.dart, do not modify by hand.
import 'dart:async';
import 'dart:js_interop';

import 'package:web/web.dart' show AbortSignal;
import 'package:sqlite3/wasm.dart' show WorkerOptions;

import '../channel.dart';
import 'messages.dart';

enum MessageType<T extends Message> {
  open<OpenRequest>(),
  connect<ConnectRequest>(),
  startFileSystemServer<StartFileSystemServer>(),
  custom<CustomRequest>(),
  fileSystemExists<FileSystemExistsQuery>(),
  fileSystemFlush<FileSystemFlushRequest>(),
  fileSystemAccess<FileSystemAccess>(),
  runQuery<RunQuery>(),
  exclusiveLock<RequestExclusiveLock>(),
  releaseLock<ReleaseLock>(),
  closeDatabase<CloseDatabase>(),
  openAdditionalConnection<OpenAdditionalConnection>(),
  simpleSuccessResponse<SimpleSuccessResponse>(),
  endpointResponse<EndpointResponse>(),
  rowsResponse<RowsResponse>(),
  errorResponse<ErrorResponse>(),
  updateRequest<UpdateStreamRequest>(),
  rollbackRequest<RollbackStreamRequest>(),
  commitRequest<CommitsStreamRequest>(),
  dedicatedCompatibilityCheck<DedicatedCompatibilityCheck>(),
  sharedCompatibilityCheck<SharedCompatibilityCheck>(),
  dedicatedInSharedCompatibilityCheck<DedicatedInSharedCompatibilityCheck>(),
  notifyUpdate<UpdateNotification>(),
  notifyCommit<CommitNotification>(),
  notifyRollback<RollbackNotification>(),
  abort<AbortRequest>(),
}

abstract base class RequestHandler {
  FutureOr<Response> handleOpen(OpenRequest request, AbortSignal abortSignal) =>
      _unsupportedRequest(request);

  FutureOr<Response> handleConnect(
    ConnectRequest request,
    AbortSignal abortSignal,
  ) => _unsupportedRequest(request);

  FutureOr<Response> handleCustom(
    CustomRequest request,
    AbortSignal abortSignal,
  ) => _unsupportedRequest(request);

  FutureOr<Response> handleFileSystemExists(
    FileSystemExistsQuery request,
    AbortSignal abortSignal,
  ) => _unsupportedRequest(request);

  FutureOr<Response> handleFileSystemFlush(
    FileSystemFlushRequest request,
    AbortSignal abortSignal,
  ) => _unsupportedRequest(request);

  FutureOr<Response> handleFileSystemAccess(
    FileSystemAccess request,
    AbortSignal abortSignal,
  ) => _unsupportedRequest(request);

  FutureOr<Response> handleRunQuery(
    RunQuery request,
    AbortSignal abortSignal,
  ) => _unsupportedRequest(request);

  FutureOr<Response> handleExclusiveLock(
    RequestExclusiveLock request,
    AbortSignal abortSignal,
  ) => _unsupportedRequest(request);

  FutureOr<Response> handleReleaseLock(
    ReleaseLock request,
    AbortSignal abortSignal,
  ) => _unsupportedRequest(request);

  FutureOr<Response> handleCloseDatabase(
    CloseDatabase request,
    AbortSignal abortSignal,
  ) => _unsupportedRequest(request);

  FutureOr<Response> handleOpenAdditionalConnection(
    OpenAdditionalConnection request,
    AbortSignal abortSignal,
  ) => _unsupportedRequest(request);

  FutureOr<Response> handleUpdateRequest(
    UpdateStreamRequest request,
    AbortSignal abortSignal,
  ) => _unsupportedRequest(request);

  FutureOr<Response> handleRollbackRequest(
    RollbackStreamRequest request,
    AbortSignal abortSignal,
  ) => _unsupportedRequest(request);

  FutureOr<Response> handleCommitRequest(
    CommitsStreamRequest request,
    AbortSignal abortSignal,
  ) => _unsupportedRequest(request);

  FutureOr<Response> handleDedicatedCompatibilityCheck(
    DedicatedCompatibilityCheck request,
    AbortSignal abortSignal,
  ) => _unsupportedRequest(request);

  FutureOr<Response> handleSharedCompatibilityCheck(
    SharedCompatibilityCheck request,
    AbortSignal abortSignal,
  ) => _unsupportedRequest(request);

  FutureOr<Response> handleDedicatedInSharedCompatibilityCheck(
    DedicatedInSharedCompatibilityCheck request,
    AbortSignal abortSignal,
  ) => _unsupportedRequest(request);

  Future<Never> _unsupportedRequest(Request request) {
    return Future.error(ArgumentError('Unsupported request ${request.type}'));
  }

  FutureOr<Response> dispatchRequest(Request request, AbortSignal abortSignal) {
    switch (request.type) {
      case 'open':
        return handleOpen(request as OpenRequest, abortSignal);
      case 'connect':
        return handleConnect(request as ConnectRequest, abortSignal);
      case 'custom':
        return handleCustom(request as CustomRequest, abortSignal);
      case 'fileSystemExists':
        return handleFileSystemExists(
          request as FileSystemExistsQuery,
          abortSignal,
        );
      case 'fileSystemFlush':
        return handleFileSystemFlush(
          request as FileSystemFlushRequest,
          abortSignal,
        );
      case 'fileSystemAccess':
        return handleFileSystemAccess(request as FileSystemAccess, abortSignal);
      case 'runQuery':
        return handleRunQuery(request as RunQuery, abortSignal);
      case 'exclusiveLock':
        return handleExclusiveLock(
          request as RequestExclusiveLock,
          abortSignal,
        );
      case 'releaseLock':
        return handleReleaseLock(request as ReleaseLock, abortSignal);
      case 'closeDatabase':
        return handleCloseDatabase(request as CloseDatabase, abortSignal);
      case 'openAdditionalConnection':
        return handleOpenAdditionalConnection(
          request as OpenAdditionalConnection,
          abortSignal,
        );
      case 'updateRequest':
        return handleUpdateRequest(request as UpdateStreamRequest, abortSignal);
      case 'rollbackRequest':
        return handleRollbackRequest(
          request as RollbackStreamRequest,
          abortSignal,
        );
      case 'commitRequest':
        return handleCommitRequest(
          request as CommitsStreamRequest,
          abortSignal,
        );
      case 'dedicatedCompatibilityCheck':
        return handleDedicatedCompatibilityCheck(
          request as DedicatedCompatibilityCheck,
          abortSignal,
        );
      case 'sharedCompatibilityCheck':
        return handleSharedCompatibilityCheck(
          request as SharedCompatibilityCheck,
          abortSignal,
        );
      case 'dedicatedInSharedCompatibilityCheck':
        return handleDedicatedInSharedCompatibilityCheck(
          request as DedicatedInSharedCompatibilityCheck,
          abortSignal,
        );
      default:
        return _unsupportedRequest(request);
    }
  }
}

@anonymous
extension type _OpenRequest._(OpenRequest _) implements OpenRequest {
  external factory _OpenRequest({
    @JS('u') required String wasmUri,
    @JS('d') required String databaseName,
    @JS('s') required JSString storageMode,
    @JS('o') required bool onlyOpenVfs,
    @JS('a') required JSAny? additionalData,
    @JS('i') required int requestId,
    @JS('t') required String type,
  });
}
OpenRequest newOpenRequest({
  required String wasmUri,
  required String databaseName,
  required JSString storageMode,
  required bool onlyOpenVfs,
  required JSAny? additionalData,
  required int requestId,
}) {
  return _OpenRequest(
    wasmUri: wasmUri,
    databaseName: databaseName,
    storageMode: storageMode,
    onlyOpenVfs: onlyOpenVfs,
    additionalData: additionalData,
    requestId: requestId,
    type: 'open',
  );
}

@anonymous
extension type _ConnectRequest._(ConnectRequest _) implements ConnectRequest {
  external factory _ConnectRequest({
    @JS('r') required WebEndpoint endpoint,
    @JS('i') required int requestId,
    @JS('d') required int? databaseId,
    @JS('t') required String type,
  });
}
ConnectRequest newConnectRequest({
  required WebEndpoint endpoint,
  required int requestId,
  required int? databaseId,
}) {
  return _ConnectRequest(
    endpoint: endpoint,
    requestId: requestId,
    databaseId: databaseId,
    type: 'connect',
  );
}

@anonymous
extension type _StartFileSystemServer._(StartFileSystemServer _)
    implements StartFileSystemServer {
  external factory _StartFileSystemServer({
    @JS('a') required WorkerOptions options,
    @JS('t') required String type,
  });
}
StartFileSystemServer newStartFileSystemServer({
  required WorkerOptions options,
}) {
  return _StartFileSystemServer(
    options: options,
    type: 'startFileSystemServer',
  );
}

@anonymous
extension type _CustomRequest._(CustomRequest _) implements CustomRequest {
  external factory _CustomRequest({
    @JS('r') required JSAny? payload,
    @JS('z') required int? lockId,
    @JS('i') required int requestId,
    @JS('d') required int? databaseId,
    @JS('t') required String type,
  });
}
CustomRequest newCustomRequest({
  required JSAny? payload,
  required int? lockId,
  required int requestId,
  required int? databaseId,
}) {
  return _CustomRequest(
    payload: payload,
    lockId: lockId,
    requestId: requestId,
    databaseId: databaseId,
    type: 'custom',
  );
}

@anonymous
extension type _FileSystemExistsQuery._(FileSystemExistsQuery _)
    implements FileSystemExistsQuery {
  external factory _FileSystemExistsQuery({
    @JS('f') required int fsType,
    @JS('i') required int requestId,
    @JS('d') required int? databaseId,
    @JS('t') required String type,
  });
}
FileSystemExistsQuery newFileSystemExistsQuery({
  required int fsType,
  required int requestId,
  required int? databaseId,
}) {
  return _FileSystemExistsQuery(
    fsType: fsType,
    requestId: requestId,
    databaseId: databaseId,
    type: 'fileSystemExists',
  );
}

@anonymous
extension type _FileSystemFlushRequest._(FileSystemFlushRequest _)
    implements FileSystemFlushRequest {
  external factory _FileSystemFlushRequest({
    @JS('i') required int requestId,
    @JS('d') required int? databaseId,
    @JS('t') required String type,
  });
}
FileSystemFlushRequest newFileSystemFlushRequest({
  required int requestId,
  required int? databaseId,
}) {
  return _FileSystemFlushRequest(
    requestId: requestId,
    databaseId: databaseId,
    type: 'fileSystemFlush',
  );
}

@anonymous
extension type _FileSystemAccess._(FileSystemAccess _)
    implements FileSystemAccess {
  external factory _FileSystemAccess({
    @JS('b') required JSArrayBuffer? buffer,
    @JS('f') required int fsType,
    @JS('i') required int requestId,
    @JS('d') required int? databaseId,
    @JS('t') required String type,
  });
}
FileSystemAccess newFileSystemAccess({
  required JSArrayBuffer? buffer,
  required int fsType,
  required int requestId,
  required int? databaseId,
}) {
  return _FileSystemAccess(
    buffer: buffer,
    fsType: fsType,
    requestId: requestId,
    databaseId: databaseId,
    type: 'fileSystemAccess',
  );
}

@anonymous
extension type _RunQuery._(RunQuery _) implements RunQuery {
  external factory _RunQuery({
    @JS('s') required String sql,
    @JS('p') required JSArray parameters,
    @JS('v') required JSArrayBuffer? typeVector,
    @JS('z') required int? lockId,
    @JS('r') required bool returnRows,
    @JS('c') required bool checkInTransaction,
    @JS('i') required int requestId,
    @JS('d') required int? databaseId,
    @JS('t') required String type,
  });
}
RunQuery newRunQuery({
  required String sql,
  required JSArray parameters,
  required JSArrayBuffer? typeVector,
  required int? lockId,
  required bool returnRows,
  required bool checkInTransaction,
  required int requestId,
  required int? databaseId,
}) {
  return _RunQuery(
    sql: sql,
    parameters: parameters,
    typeVector: typeVector,
    lockId: lockId,
    returnRows: returnRows,
    checkInTransaction: checkInTransaction,
    requestId: requestId,
    databaseId: databaseId,
    type: 'runQuery',
  );
}

@anonymous
extension type _RequestExclusiveLock._(RequestExclusiveLock _)
    implements RequestExclusiveLock {
  external factory _RequestExclusiveLock({
    @JS('i') required int requestId,
    @JS('d') required int? databaseId,
    @JS('t') required String type,
  });
}
RequestExclusiveLock newRequestExclusiveLock({
  required int requestId,
  required int? databaseId,
}) {
  return _RequestExclusiveLock(
    requestId: requestId,
    databaseId: databaseId,
    type: 'exclusiveLock',
  );
}

@anonymous
extension type _ReleaseLock._(ReleaseLock _) implements ReleaseLock {
  external factory _ReleaseLock({
    @JS('z') required int lockId,
    @JS('i') required int requestId,
    @JS('d') required int? databaseId,
    @JS('t') required String type,
  });
}
ReleaseLock newReleaseLock({
  required int lockId,
  required int requestId,
  required int? databaseId,
}) {
  return _ReleaseLock(
    lockId: lockId,
    requestId: requestId,
    databaseId: databaseId,
    type: 'releaseLock',
  );
}

@anonymous
extension type _CloseDatabase._(CloseDatabase _) implements CloseDatabase {
  external factory _CloseDatabase({
    @JS('i') required int requestId,
    @JS('d') required int? databaseId,
    @JS('t') required String type,
  });
}
CloseDatabase newCloseDatabase({
  required int requestId,
  required int? databaseId,
}) {
  return _CloseDatabase(
    requestId: requestId,
    databaseId: databaseId,
    type: 'closeDatabase',
  );
}

@anonymous
extension type _OpenAdditionalConnection._(OpenAdditionalConnection _)
    implements OpenAdditionalConnection {
  external factory _OpenAdditionalConnection({
    @JS('i') required int requestId,
    @JS('d') required int? databaseId,
    @JS('t') required String type,
  });
}
OpenAdditionalConnection newOpenAdditionalConnection({
  required int requestId,
  required int? databaseId,
}) {
  return _OpenAdditionalConnection(
    requestId: requestId,
    databaseId: databaseId,
    type: 'openAdditionalConnection',
  );
}

@anonymous
extension type _SimpleSuccessResponse._(SimpleSuccessResponse _)
    implements SimpleSuccessResponse {
  external factory _SimpleSuccessResponse({
    @JS('r') required JSAny? response,
    @JS('i') required int requestId,
    @JS('t') required String type,
  });
}
SimpleSuccessResponse newSimpleSuccessResponse({
  required JSAny? response,
  required int requestId,
}) {
  return _SimpleSuccessResponse(
    response: response,
    requestId: requestId,
    type: 'simpleSuccessResponse',
  );
}

@anonymous
extension type _EndpointResponse._(EndpointResponse _)
    implements EndpointResponse {
  external factory _EndpointResponse({
    @JS('r') required WebEndpoint endpoint,
    @JS('i') required int requestId,
    @JS('t') required String type,
  });
}
EndpointResponse newEndpointResponse({
  required WebEndpoint endpoint,
  required int requestId,
}) {
  return _EndpointResponse(
    endpoint: endpoint,
    requestId: requestId,
    type: 'endpointResponse',
  );
}

@anonymous
extension type _RowsResponse._(RowsResponse _) implements RowsResponse {
  external factory _RowsResponse({
    @JS('c') required JSArray<JSString>? columnNames,
    @JS('n') required JSArray<JSString?>? tableNames,
    @JS('v') required JSArrayBuffer? typeVector,
    @JS('r') required JSArray<JSArray<JSAny?>>? rows,
    @JS('x') required bool autoCommit,
    @JS('y') required int lastInsertRowId,
    @JS('i') required int requestId,
    @JS('t') required String type,
  });
}
RowsResponse newRowsResponse({
  required JSArray<JSString>? columnNames,
  required JSArray<JSString?>? tableNames,
  required JSArrayBuffer? typeVector,
  required JSArray<JSArray<JSAny?>>? rows,
  required bool autoCommit,
  required int lastInsertRowId,
  required int requestId,
}) {
  return _RowsResponse(
    columnNames: columnNames,
    tableNames: tableNames,
    typeVector: typeVector,
    rows: rows,
    autoCommit: autoCommit,
    lastInsertRowId: lastInsertRowId,
    requestId: requestId,
    type: 'rowsResponse',
  );
}

@anonymous
extension type _ErrorResponse._(ErrorResponse _) implements ErrorResponse {
  external factory _ErrorResponse({
    @JS('e') required String message,
    @JS('s') required JSNumber? serializedExceptionType,
    @JS('r') required JSAny? serializedException,
    @JS('i') required int requestId,
    @JS('t') required String type,
  });
}
ErrorResponse newErrorResponse({
  required String message,
  required JSNumber? serializedExceptionType,
  required JSAny? serializedException,
  required int requestId,
}) {
  return _ErrorResponse(
    message: message,
    serializedExceptionType: serializedExceptionType,
    serializedException: serializedException,
    requestId: requestId,
    type: 'errorResponse',
  );
}

@anonymous
extension type _UpdateStreamRequest._(UpdateStreamRequest _)
    implements UpdateStreamRequest {
  external factory _UpdateStreamRequest({
    @JS('a') required bool action,
    @JS('i') required int requestId,
    @JS('d') required int? databaseId,
    @JS('t') required String type,
  });
}
UpdateStreamRequest newUpdateStreamRequest({
  required bool action,
  required int requestId,
  required int? databaseId,
}) {
  return _UpdateStreamRequest(
    action: action,
    requestId: requestId,
    databaseId: databaseId,
    type: 'updateRequest',
  );
}

@anonymous
extension type _RollbackStreamRequest._(RollbackStreamRequest _)
    implements RollbackStreamRequest {
  external factory _RollbackStreamRequest({
    @JS('a') required bool action,
    @JS('i') required int requestId,
    @JS('d') required int? databaseId,
    @JS('t') required String type,
  });
}
RollbackStreamRequest newRollbackStreamRequest({
  required bool action,
  required int requestId,
  required int? databaseId,
}) {
  return _RollbackStreamRequest(
    action: action,
    requestId: requestId,
    databaseId: databaseId,
    type: 'rollbackRequest',
  );
}

@anonymous
extension type _CommitsStreamRequest._(CommitsStreamRequest _)
    implements CommitsStreamRequest {
  external factory _CommitsStreamRequest({
    @JS('a') required bool action,
    @JS('i') required int requestId,
    @JS('d') required int? databaseId,
    @JS('t') required String type,
  });
}
CommitsStreamRequest newCommitsStreamRequest({
  required bool action,
  required int requestId,
  required int? databaseId,
}) {
  return _CommitsStreamRequest(
    action: action,
    requestId: requestId,
    databaseId: databaseId,
    type: 'commitRequest',
  );
}

@anonymous
extension type _DedicatedCompatibilityCheck._(DedicatedCompatibilityCheck _)
    implements DedicatedCompatibilityCheck {
  external factory _DedicatedCompatibilityCheck({
    @JS('d') required String? databaseName,
    @JS('i') required int requestId,
    @JS('t') required String type,
  });
}
DedicatedCompatibilityCheck newDedicatedCompatibilityCheck({
  required String? databaseName,
  required int requestId,
}) {
  return _DedicatedCompatibilityCheck(
    databaseName: databaseName,
    requestId: requestId,
    type: 'dedicatedCompatibilityCheck',
  );
}

@anonymous
extension type _SharedCompatibilityCheck._(SharedCompatibilityCheck _)
    implements SharedCompatibilityCheck {
  external factory _SharedCompatibilityCheck({
    @JS('d') required String? databaseName,
    @JS('i') required int requestId,
    @JS('t') required String type,
  });
}
SharedCompatibilityCheck newSharedCompatibilityCheck({
  required String? databaseName,
  required int requestId,
}) {
  return _SharedCompatibilityCheck(
    databaseName: databaseName,
    requestId: requestId,
    type: 'sharedCompatibilityCheck',
  );
}

@anonymous
extension type _DedicatedInSharedCompatibilityCheck._(
  DedicatedInSharedCompatibilityCheck _
) implements DedicatedInSharedCompatibilityCheck {
  external factory _DedicatedInSharedCompatibilityCheck({
    @JS('d') required String? databaseName,
    @JS('i') required int requestId,
    @JS('t') required String type,
  });
}
DedicatedInSharedCompatibilityCheck newDedicatedInSharedCompatibilityCheck({
  required String? databaseName,
  required int requestId,
}) {
  return _DedicatedInSharedCompatibilityCheck(
    databaseName: databaseName,
    requestId: requestId,
    type: 'dedicatedInSharedCompatibilityCheck',
  );
}

@anonymous
extension type _UpdateNotification._(UpdateNotification _)
    implements UpdateNotification {
  external factory _UpdateNotification({
    @JS('k') required int updateKind,
    @JS('u') required String updateTableName,
    @JS('r') required int rowId,
    @JS('d') required int databaseId,
    @JS('t') required String type,
  });
}
UpdateNotification newUpdateNotification({
  required int updateKind,
  required String updateTableName,
  required int rowId,
  required int databaseId,
}) {
  return _UpdateNotification(
    updateKind: updateKind,
    updateTableName: updateTableName,
    rowId: rowId,
    databaseId: databaseId,
    type: 'notifyUpdate',
  );
}

@anonymous
extension type _CommitNotification._(CommitNotification _)
    implements CommitNotification {
  external factory _CommitNotification({
    @JS('d') required int databaseId,
    @JS('t') required String type,
  });
}
CommitNotification newCommitNotification({required int databaseId}) {
  return _CommitNotification(databaseId: databaseId, type: 'notifyCommit');
}

@anonymous
extension type _RollbackNotification._(RollbackNotification _)
    implements RollbackNotification {
  external factory _RollbackNotification({
    @JS('d') required int databaseId,
    @JS('t') required String type,
  });
}
RollbackNotification newRollbackNotification({required int databaseId}) {
  return _RollbackNotification(databaseId: databaseId, type: 'notifyRollback');
}

@anonymous
extension type _AbortRequest._(AbortRequest _) implements AbortRequest {
  external factory _AbortRequest({
    @JS('i') required int requestId,
    @JS('t') required String type,
  });
}
AbortRequest newAbortRequest({required int requestId}) {
  return _AbortRequest(requestId: requestId, type: 'abort');
}

@JS('ArrayBuffer')
external JSFunction get _arrayBufferConstructor;
JSArray<JSAny> extractTransferrable(Message message) {
  final result = JSArray<JSAny>();
  switch (message.type) {
    case 'connect':
      result.add((message as ConnectRequest).endpoint.port);
      break;
    case 'fileSystemAccess':
      if ((message as FileSystemAccess).buffer case final e?) result.add(e);
      break;
    case 'runQuery':
      if ((message as RunQuery).typeVector case final e?) result.add(e);
      break;
    case 'simpleSuccessResponse':
      if ((message as SimpleSuccessResponse).response case JSAny a
          when a.instanceof(_arrayBufferConstructor)) {
        result.add(a);
      }
      break;
    case 'endpointResponse':
      result.add((message as EndpointResponse).endpoint.port);
      break;
    case 'rowsResponse':
      if ((message as RowsResponse).typeVector case final e?) result.add(e);
      break;
  }
  return result;
}

T dispatchMessage<T>(
  Message msg, {
  required T Function(StartFileSystemServer) whenStartFileSystemServer,
  required T Function(AbortRequest) whenAbortRequest,
  required T Function(Notification) whenNotification,
  required T Function(Response) whenResponse,
  required T Function(Request) whenRequest,
}) {
  switch (msg.type) {
    case 'startFileSystemServer':
      return whenStartFileSystemServer(msg as StartFileSystemServer);
    case 'abort':
      return whenAbortRequest(msg as AbortRequest);
    case 'notifyUpdate':
    case 'notifyCommit':
    case 'notifyRollback':
      return whenNotification(msg as Notification);
    case 'simpleSuccessResponse':
    case 'endpointResponse':
    case 'rowsResponse':
    case 'errorResponse':
      return whenResponse(msg as Response);
    default:
      return whenRequest(msg as Request);
  }
}
