name: flutter_cocoapods
publish_to: 'none'
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  common:
  sqlite3:
  sqlite3_flutter_libs:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  config:
    enable-swift-package-manager: false
