targets:
  $default:
    sources:
      include:
        - lib/**
        - example/web/**
        - $package$
    builders:
      build_web_compilers:entrypoint:
        options:
          compilers:
            dart2js:
        generate_for:
          include:
            - "example/web/**"
